### ISSUE TITLE
运行出错，分辨率设置正确

### ISSUE THREAD

**Issue by zyaloon** [Skyexu/TopSup#105]
Traceback (most recent call last):
  File "GetQuestionTessAndroid.py", line 35, in <module>
    m1 = Thread(methods.run_algorithm(0, question, choices))
  File "D:\pyback\TopSup-master\common\methods.py", line 81, in run_algorithm
    open_webbrowser(question)
  File "D:\pyback\TopSup-master\common\methods.py", line 17, in open_webbrowser
    webbrowser.open('https://baidu.com/s?wd=' + urllib.quote(question))
  File "C:\Python27\lib\urllib.py", line 1299, in quote
    return ''.join(map(quoter, s))
KeyError: u'\u201c'

**Comment by RoyLaw** [comment]
建议还是用python3来运行

**Comment by zyaloon** [comment]
都是泪，已经在重装了
