### ISSUE TITLE
报错了 大神进来看错误代码

### ISSUE THREAD

**Issue by zq019633** [Skyexu/TopSup#106]
Traceback (most recent call last):
  File "/Users/zhouqiang/Desktop/TopSup-master/GetQuestionTessAndroid.py", line 20, in <module>
    question, choices = ocr.ocr_img(img)
  File "/Users/zhouqiang/Desktop/TopSup-master/common/ocr.py", line 76, in ocr_img
    question = pytesseract.image_to_string(question_im, lang='chi_sim', config=tessdata_dir_config)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pytesseract/pytesseract.py", line 125, in image_to_string
    raise TesseractError(status, errors)
pytesseract.pytesseract.TesseractError: (1, "Failed loading language 'chi_sim'\nTesseract couldn't load any languages!\nCould not initialize tesseract.")

我已经安装 中文简体库了 放在了 /usr/local/Cellar/tesseract/3.05.01/share/tessdata 
这个目录下  名字是chi_sim.traineddata   需要改动什么吗

**Comment by tae44** [comment]
ocr.py下的tesseract路径看看设置对了嘛,默认是Windows系统的
