### ISSUE TITLE
iOS下报错，少安装了什么吗？

### ISSUE THREAD

**Issue by konanxu** [Skyexu/TopSup#109]
Traceback (most recent call last):
  File "GetQuestionTessIos.py", line 9, in <module>
    from common import  ocr, methods
  File "/Users/konan/konan/HookTools/TopSup/common/methods.py", line 9, in <module>
    import urllib.parse
ImportError: No module named parse

**Comment by RoyLaw** [comment]
import urllib.parse -> import urllib
试试~

**Comment by jayking0912** [comment]
还有我运行发现 需要 添加 .encode('utf-8') 问题，可能跟我mac有关，win不知道

**Comment by konanxu** [comment]
已经没有问题了，thks。但目前和其他几个人说的一样只有二个选项计数，而且打开百度是首页，未加入搜索词
