### ISSUE TITLE
运行python GetQuestionTessAndroid.py就出错啦

### ISSUE THREAD

**Issue by Miracle-Ant** [Skyexu/TopSup#112]
D:\TopSup-master>python GetQuestionTessAndroid.py
采用方式 1 获取截图
Traceback (most recent call last):
  File "GetQuestionTessAndroid.py", line 20, in <module>
    question, choices = ocr.ocr_img(img)
  File "D:\TopSup-master\common\ocr.py", line 76, in ocr_img
    question = pytesseract.image_to_string(question_im, lang='chi_sim', config=tessdata_dir_config)
  File "D:\Python\python\lib\site-packages\pytesseract\pytesseract.py", line 125, in image_to_string
    raise TesseractError(status, errors)
pytesseract.pytesseract.TesseractError: (1, 'Error opening data file D:\\Tesseract-OCR\\tessdata/chi_sim.traineddata')

**Comment by FRANKzsx** [comment]
没装中文包，你看看前面的issue啊
