### ISSUE TITLE
pop index out of range

### ISSUE THREAD

**Issue by ning-chao** [Skyexu/TopSup#113]
D:\TopSup-master>python GetQuestionTessAndroid.py
采用方式 1 获取截图
Traceback (most recent call last):
  File "GetQuestionTessAndroid.py", line 20, in <module>
    question, choices = ocr.ocr_img(img)
  File "D:\TopSup-master\common\ocr.py", line 95, in ocr_img
    choices.pop(1)
IndexError: pop index out of range

**Comment by dreamsoday** [comment]
你这个问题解决了吗？问题一样

**Comment by Miracle-Ant** [comment]
现在是能识别屏幕东西，但搜出来的东西是乱的
