### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by fengx123** [Skyexu/TopSup#12]
运行GetQuestionTessAndroid.py的时候21行报错了：question, choices = ocr.ocr_img(img)，大神知道是为啥吗？

**Comment by Skyexu** [comment]
@fengx123 你好，请复制运行错误详情

**Comment by fengx123** [comment]
Traceback (most recent call last):
  File "C:\Users\fengxuan\Desktop\TopSup-master\GetQuestionTessAndroid.py", line
 21, in <module>
    question, choices = ocr.ocr_img(img)
  File "C:\Users\fengxuan\Desktop\TopSup-master\common\ocr.py", line 64, in ocr_
img
    question = pytesseract.image_to_string(question_im, lang='chi_sim', config=t
essdata_dir_config)
  File "C:\Python27\lib\site-packages\pytesseract\pytesseract.py", line 125, in
image_to_string
    raise TesseractError(status, errors)
pytesseract.pytesseract.TesseractError: (1, u'Error opening data file C:\\Progra
m Files (x86)\\Tesseract-OCR\\tessdata/chi_sim.traineddata')

**Comment by yyBeta** [comment]
λ python GetQuestionTessAndroid.py
采用方式 1 获取截图
Traceback (most recent call last):
  File "GetQuestionTessAndroid.py", line 21, in <module>
    question, choices = ocr.ocr_img(img)
  File "E:\Projects\Python\TopSup\common\ocr.py", line 64, in ocr_img
    question = pytesseract.image_to_string(question_im, lang='chi_sim', config=tessdata_dir_config)
  File "D:\Runtime\IntelPython3\envs\dati\lib\site-packages\pytesseract\pytesseract.py", line 122, in image_to_string
    config=config)
  File "D:\Runtime\IntelPython3\envs\dati\lib\site-packages\pytesseract\pytesseract.py", line 46, in run_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "D:\Runtime\IntelPython3\envs\dati\lib\subprocess.py", line 709, in __init__

    restore_signals, start_new_session)
  File "D:\Runtime\IntelPython3\envs\dati\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
PermissionError: [WinError 5] 拒绝访问。

**Comment by harman-DarrenChen** [comment]
同问

**Comment by asseywang** [comment]
@fengx123 环境变量
pytesseract.pytesseract.TesseractError: (1, 'Error opening data file \Program Files (x86)\Tesseract-OCR\tessdata/chi_sim.traineddata')
解决方案：
设置环境变量 TESSDATA_PREFIX 
C:\Program Files (x86)\Tesseract-OCR\tessdata(供参考，以实际安装路径为准)

**Comment by asseywang** [comment]
@yyBeta 你的问题看起来也是Tesseract的环境变量或目录权限问题

**Comment by ray0807** [comment]
哥们请看报错啊～
找不到中文训练数据集，下一个放到对应目录即可～
下载  https://raw.githubusercontent.com/tesseract-ocr/tessdata/master/chi_sim.traineddata

**Comment by umbradyj** [comment]
默认安装的adb怎么不运行呢
D:\TopSup-master\TopSup-master>GetQuestionTessAndroid.py
'adb' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Traceback (most recent call last):
  File "D:\TopSup-master\TopSup-master\GetQuestionTessAndroid.py", line 15, in
module>
    screenshot.check_screenshot()
  File "D:\TopSup-master\TopSup-master\common\screenshot.py", line 54, in check
screenshot
    pull_screenshot()
  File "D:\TopSup-master\TopSup-master\common\screenshot.py", line 33, in pull_
creenshot
    f = open('screenshot.png', 'wb')
PermissionError: [Errno 13] Permission denied: 'screenshot.png'

**Comment by Deadalusmask** [comment]
@yyBeta  遇到了一样的问题，请问找到解决方法了吗
adb和tesseract都正常 也使用管理员权限打开的powershell
