### ISSUE TITLE
 ocr methods 怎么安装啊

### ISSUE THREAD

**Issue by ZackKingS** [Skyexu/TopSup#123]
Traceback (most recent call last):
  File "/Users/bochaoceng/Desktop/pythonProj/jump/TopSup.py", line 9, in <module>
    from common import  ocr, methods
ImportError: No module named common

**Comment by cncal** [comment]
请问你对源码有没有做什么改动，比如删除 `common` 文件夹下的 `__init__.py` 文件，这个文件会把 `common` 文件夹变为一个 Python 模块用于引用。

**Comment by ZackKingS** [comment]
原来这个库在 common里面 .....  ,不过有报错了
File "GetQuestionTessIos.py", line 9, in <module>
    from common import  ocr, methods
  File "/Users/bochaoceng/Desktop/TopSup-master/common/methods.py", line 9, in <module>
    import urllib.parse
ImportError: No module named parse
大神麻烦看一下 是怎么添加这个依赖啊

**Comment by ZackKingS** [comment]
是要用 python3 么

**Comment by cncal** [comment]
试试呢，http://blog.csdn.net/testcs_dn/article/details/55807101 这篇文章也这么说的

**Comment by ZackKingS** [comment]
好的 谢啦
