### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by liudada2017** [Skyexu/TopSup#137]
大神看一下这个是什么原因，为什么会报这个错，是因为百度api的调用次数超了吗？但是我另一个程序掉的起呢！就这个程序跑不起来

**Comment by liudada2017** [comment]
这个是截图

**Comment by liudada2017** [comment]
上传图片

**Comment by liudada2017** [comment]
这个是报错代码：

"D:\Program Files (x86)\python\python.exe" E:/Python学习程序/TopSup-master/GetQuestionAndroid.py
采用方式 1 获取截图
Traceback (most recent call last):
  File "E:/Python学习程序/TopSup-master/GetQuestionAndroid.py", line 37, in <module>
    question, choices = ocr.ocr_img_baidu(img, config)
  File "E:\Python学习程序\TopSup-master\common\ocr.py", line 188, in ocr_img_baidu
    words_result = response['words_result']
KeyError: 'words_result'

Process finished with exit code 1

**Comment by Skyexu** [comment]
打印 baidu 返回的信息看看吧

**Comment by liudada2017** [comment]
我打的 ocr.py中的  
response = client.basicGeneral(image_data)
 print(response)

打印结果：{'error_code': 14, 'error_msg': 'IAM Certification failed'}

是打印这个吗？
