### ISSUE TITLE
外挂启动后报错

### ISSUE THREAD

**Issue by wangpeng1017** [Skyexu/TopSup#23]
外挂启动后报错如下，请问是什么原因？
------
答题外挂已启动
采用方式 2 获取截图
Traceback (most recent call last):
  File "/Users/wangpeng52/Downloads/TopSup-master/GetQuestionTessAndroid.py", line 21, in <module>
    question, choices = ocr.ocr_img(img)
  File "/Users/wangpeng52/Downloads/TopSup-master/common/ocr.py", line 64, in ocr_img
    question = pytesseract.image_to_string(question_im, lang='chi_sim', config=tessdata_dir_config)
  File "/anaconda3/lib/python3.6/site-packages/pytesseract/pytesseract.py", line 122, in image_to_string
    config=config)
  File "/anaconda3/lib/python3.6/site-packages/pytesseract/pytesseract.py", line 46, in run_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/anaconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\Tesseract-OCR\\tesseract': 'C:\\Program Files (x86)\\Tesseract-OCR\\tesseract'

**Comment by wangpeng1017** [comment]
上面两个问题解决了：Mac需要修改路径，且需要安装chi_sim.traineddata
但是
又出现一个新的问题。。。如下
答题外挂已启动
Traceback (most recent call last):
  File "/Users/wangpeng52/Downloads/TopSup-master/GetQuestionTessAndroid.py", line 16, in <module>
    screenshot.check_screenshot()
  File "/Users/wangpeng52/Downloads/TopSup-master/common/screenshot.py", line 54, in check_screenshot
    pull_screenshot()
  File "/Users/wangpeng52/Downloads/TopSup-master/common/screenshot.py", line 33, in pull_screenshot
    f = open('screenshot.png', 'wb')
PermissionError: [Errno 13] Permission denied: 'screenshot.png'

**Comment by dreamsoday** [comment]
用方式 3 获取截图
Traceback (most recent call last):
  File "GetQuestionTessAndroid.py", line 20, in <module>
    question, choices = ocr.ocr_img(img)
  File "/Users/liuyang/Downloads/TopSup-master/common/ocr.py", line 88, in ocr_img
    if (choices[0].endswith('?')):
IndexError: list index out of range
这个是怎么解决的
