### ISSUE TITLE
FileNotFoundError: [WinError 2] 系统找不到指定的文件

### ISSUE THREAD

**Issue by chensongz** [Skyexu/TopSup#27]
Windows环境下运行报错：
```
python GetQuestionTessAndroid.py
采用方式 2 获取截图
Traceback (most recent call last):
  File "GetQuestionTessAndroid.py", line 20, in <module>
    question, choices = ocr.ocr_img(img)
  File "D:\Download\ZSDT\code\TopSup\common\ocr.py", line 64, in ocr_img
    question = pytesseract.image_to_string(question_im, lang='chi_sim', config=tessdata_dir_config)
  File "D:\Project\Python3\lib\site-packages\pytesseract\pytesseract.py", line 123, in image_to_string
    config=config)
  File "D:\Project\Python3\lib\site-packages\pytesseract\pytesseract.py", line 47, in run_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "D:\Project\Python3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "D:\Project\Python3\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
```

这个是tesseract路径问题吗？已经填加了PATH，当前可执行tesseract
tesseract路径配置
```
# tesseract 路径
pytesseract.pytesseract.tesseract_cmd = 'D:\\Project\\Tesseract-OCR\\tesseract'
# 语言包目录
tessdata_dir_config = '--tessdata-dir "D:\\Project\\Tesseract-OCR\\tessdata" --psm 6'
```

README中提到的依赖已安装

**Comment by chensongz** [comment]
找到原因了，我修改是的`GetTitleTessAndroid.py`中tesseract的路径，而实际运行版本是调用的`ocr.py`中的tesseract路径，修改`ocr.py`中的即可解决。
