### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by zuojinbo** [Skyexu/TopSup#36]
(python36) E:\AssisiTool\TopSup-master>GetQuestionTessAndroid.py
閲囩敤鏂瑰紡 2 鑾峰彇鎴浘
Traceback (most recent call last):
  File "E:\AssisiTool\TopSup-master\GetQuestionTessAndroid.py", line 20, in <mod
ule>
    question, choices = ocr.ocr_img(img)
  File "E:\AssisiTool\TopSup-master\common\ocr.py", line 64, in ocr_img
    question = pytesseract.image_to_string(question_im, lang='chi_sim', config=t
essdata_dir_config)
  File "C:\Python27\lib\site-packages\pytesseract\pytesseract.py", line 122, in
image_to_string
    config=config)
  File "C:\Python27\lib\site-packages\pytesseract\pytesseract.py", line 46, in r
un_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "C:\Python27\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 959, in _execute_child
    startupinfo)
WindowsError: [Error 2]

**Comment by zuojinbo** [comment]
已解决，不过题目不是乱码，选项是乱码醉了

**Comment by octopuszy** [comment]
请问如何解决
