### ISSUE TITLE
能出一个Mac+iOS的详细步骤嘛   我的老有问题

### ISSUE THREAD

**Issue by StrongManCoder** [Skyexu/TopSup#37]
➜  TopSup-master python3 GetQuestionTessIos.py
Traceback (most recent call last):
  File "GetQuestionTessIos.py", line 23, in <module>
    question, choices = ocr.ocr_img(img)
  File "/Users/Mac/Downloads/TopSup-master/common/ocr.py", line 64, in ocr_img
    question = pytesseract.image_to_string(question_im, lang='chi_sim', config=tessdata_dir_config)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pytesseract/pytesseract.py", line 122, in image_to_string
    config=config)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pytesseract/pytesseract.py", line 46, in run_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\Tesseract-OCR\\tesseract'

**Comment by nyakokishi** [comment]
mac 上你需要将 tesseract 添加到环境变量中，或在代码直接设置例如：`pytesseract.pytesseract.tesseract_cmd = '/usr/local/bin/tesseract'`

首先`brew install --with-training-tools tesseract #同时安装附加组件`，安装完成后默认有了 `eng.traineddata`，由于我们识别的是简体中文，所以你还需要简体中文的训练数据，在 [https://github.com/tesseract-ocr/tessdata](https://github.com/tesseract-ocr/tessdata) 下载 `chi_sim.traineddata`，并移动到`eng.traineddata`同一目录下，`FileNotFoundError `就不会再出现了

**Comment by qinyang1018** [comment]
现在已经能跑起来了,但是识别中文乱码。。  看了现有的issuess但是还是没有解决
