### ISSUE TITLE
求助，这个错误是怎么回事？要怎样处理？

### ISSUE THREAD

**Issue by distrow** [Skyexu/TopSup#44]
C:\Users\Administrator\Desktop\TopSup-master\TopSup-master>python GetQuestionTes
sAndroid.py
采用方式 2 获取截图
Traceback (most recent call last):
  File "GetQuestionTessAndroid.py", line 20, in <module>
    question, choices = ocr.ocr_img(img)
  File "C:\Users\Administrator\Desktop\TopSup-master\TopSup-master\common\ocr.py
", line 64, in ocr_img
    question = pytesseract.image_to_string(question_im, lang='chi_sim', config=t
essdata_dir_config)
  File "C:\python3.6\lib\site-packages\pytesseract\pytesseract.py", line 122, in
 image_to_string
    config=config)
  File "C:\python3.6\lib\site-packages\pytesseract\pytesseract.py", line 46, in
run_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "C:\python3.6\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\python3.6\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by Hilpen** [comment]
`common\ocr.py`里面的
`    # tesseract 路径
    pytesseract.pytesseract.tesseract_cmd = 'D:\\Program Files\\Tesseract-OCR\\tesseract'
    # 语言包目录和参数
    tessdata_dir_config = '--tessdata-dir "C:\\Program Files\\Tesseract-OCR\\tessdata" --psm 6'`
改成自己TesseractOCR的目录

**Comment by 854133055** [comment]
http://blog.csdn.net/zhangda0000001/article/details/73608847  我的是通过文章中说的，加上shell=True搞定的

**Comment by uxual** [comment]
C:\Users\Alex>python C:\Users\Alex\Desktop\TopSup-master\TopSup-master\GetQuestionTessAndroid.py
Traceback (most recent call last):
  File "C:\Users\Alex\Desktop\TopSup-master\TopSup-master\GetQuestionTessAndroid.py", line 9, in <module>
    from common import screenshot, ocr, methods
  File "C:\Users\Alex\Desktop\TopSup-master\TopSup-master\common\methods.py", line 9, in <module>
    import urllib.parse
ImportError: No module named parse


No module named ?
