### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters 

### ISSUE THREAD

**Issue by bwpandamb** [Skyexu/TopSup#45]
Traceback (most recent call last):
  File "GetQuestionTessAndroid.py", line 32, in <module>
    m1 = Thread(methods.run_algorithm(0, question, choices))
  File "/Users/ext.charles.ma/Desktop/mm/TopSup/common/methods.py", line 74, in run_algorithm
    open_webbrowser(question)
  File "/Users/ext.charles.ma/Desktop/mm/TopSup/common/methods.py", line 11, in open_webbrowser
    webbrowser.open('https://baidu.com/s?wd=' + question)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/webbrowser.py", line 61, in open
    if browser.open(url, new, autoraise):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/webbrowser.py", line 636, in open
    osapipe.write(script)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 38-39: ordinal not in range(128)

**Comment by bwpandamb** [comment]
小白一个，前面很多坑都硬过去了，这里确实知道是编码问题，但是不知道怎么解决

**Comment by Nipi64310** [comment]
@bwpandamb  好像是因为你是 python2的版本，才有这种错误，  可以 把那些字符串转成unicode的

**Comment by asseywang** [comment]
@bwpandamb mac可以自己再装一个3.6.4

**Comment by chuli** [comment]
@bwpandamb mac brew install python3
