### ISSUE TITLE
一个报错不知道如何解决...

### ISSUE THREAD

**Issue by iamjjww** [Skyexu/TopSup#48]
C:\Users\LHTV\Desktop\TopSup-master>python GetQuestionTessAndroid.py
Traceback (most recent call last):
  File "GetQuestionTessAndroid.py", line 9, in <module>
    from common import screenshot, ocr, methods
  File "C:\Users\LHTV\Desktop\TopSup-master\common\ocr.py", line 8, in <module>
    import pytesseract
  File "C:\Python27\lib\site-packages\pytesseract\__init__.py", line 2, in <module>
    from pytesseract import image_to_string
  File "C:\Python27\lib\site-packages\pytesseract\pytesseract.py", line 9, in <module>
    import Image
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 27, in <module>
    from . import VERSION, PILLOW_VERSION, _plugins
ValueError: Attempted relative import in non-package

**Comment by Nipi64310** [comment]
@iamjjww  把common那个文件夹放到.py文件夹的位置
