### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5

### ISSUE THREAD

**Issue by 854133055** [Skyexu/TopSup#54]
`采用方式 2 获取截图

Traceback (most recent call last):
  File "GetQuestionTessAndroid.py", line 20, in <module>
    question, choices = ocr.ocr_img(img)
  File "D:\TopSup-master\common\ocr.py", line 65, in ocr_img
    question = pytesseract.image_to_string(question_im, lang='chi_sim', config=tessdata_dir_config)
  File "C:\Users\molei.li\AppData\Local\Programs\Python\Python36\lib\site-packages\pytesseract\pytesseract.py", line 124, in image_to_string
    errors = get_errors(error_string)
  File "C:\Users\molei.li\AppData\Local\Programs\Python\Python36\lib\site-packages\pytesseract\pytesseract.py", line 67, in get_errors
    error_string = error_string.decode('utf-8')
**UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 4: invalid continuation byte`**

**Comment by 854133055** [comment]
环境windows+python3.6.1

**Comment by Deadalusmask** [comment]
```
Traceback (most recent call last):
  File ".\GetQuestionTessAndroid.py", line 20, in <module>
    question, choices = ocr.ocr_img(img)
  File "D:\web\py\TopSup-master\common\ocr.py", line 63, in ocr_img
    question = pytesseract.image_to_string(question_im, lang='chi_sim', config=tessdata_dir_config)
  File "C:\Users\Deada\AppData\Local\Programs\Python\Python36\lib\site-packages\pytesseract\pytesseract.py", line 124, in image_to_string
    errors = get_errors(error_string)
  File "C:\Users\Deada\AppData\Local\Programs\Python\Python36\lib\site-packages\pytesseract\pytesseract.py", line 67, in get_errors
    error_string = error_string.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 49: invalid start byte
```
同样遇到了解码错误的问题，是tesseract还是别的的编码问题吗
