### ISSUE TITLE
Mac+iOS环境  出现的问题

### ISSUE THREAD

**Issue by StrongManCoder** [Skyexu/TopSup#58]
TopSup-master python3 GetQuestionTessIos.py
Traceback (most recent call last):
  File "GetQuestionTessIos.py", line 23, in <module>
    question, choices = ocr.ocr_img(img)
  File "/Users/Mac/Downloads/TopSup-master/common/ocr.py", line 47, in ocr_img
    question = img.crop((75, 315, 1167, 789)) # iPhone 7P
NameError: name 'img' is not defined

**Comment by StrongManCoder** [comment]
这个我解决了  是源码有句写错了  
TopSup-master/common/ocr.py", line 47, in ocr_img
question = img.crop((75, 315, 1167, 789)) # iPhone 7P       中的question = img.crop((75, 315, 1167, 789))  改成    choices_im = image.crop((75, 535, 990, 1150))就好了
