### ISSUE TITLE
历尽千辛万苦，卡在ImportError: No module named parse

### ISSUE THREAD

**Issue by bowensun** [Skyexu/TopSup#72]
MacBook-Pro-4:TopSup-master noah$ python GetQuestionTessIos.py
Traceback (most recent call last):
  File "GetQuestionTessIos.py", line 9, in <module>
    from common import  ocr, methods
  File "/Users/noah/Downloads/TopSup-master/common/methods.py", line 9, in <module>
    import urllib.parse
ImportError: No module named parse

Python 2.7 + Mac + iOS
哪位帮看下，这个怎么搞

**Comment by bowensun** [comment]
问了个白痴问题，答案

urlparse模块在Python 3中重命名为urllib.parse
所以模块在Python 2.7下你应该使用urlparse
