### ISSUE TITLE
ocr.py报错

### ISSUE THREAD

**Issue by hk10424** [Skyexu/TopSup#75]
python GetQuestionTessAndroid.py
Traceback (most recent call last):
  File "GetQuestionTessAndroid.py", line 20, in <module>
    question, choices = ocr.ocr_img(img)
  File "c:\TopSup\common\ocr.py", line 88, in ocr_img
    if (choices[0].endswith('?')):
IndexError: list index out of range

**Comment by tae44** [comment]
分辨率设置有问题
