### ISSUE TITLE
请问ocr.py的报错问题应该怎么解决？

### ISSUE THREAD

**Issue by BaiTaiBai** [Skyexu/TopSup#81]
采用方式 2 获取截图
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/TopSup-master/GetQuestionTessAndroid.py", line 20, in <module>
    question, choices = ocr.ocr_img(img)
  File "C:\Users\Administrator\Desktop\TopSup-master\common\ocr.py", line 88, in ocr_img
    if (choices[0].endswith('?')):
IndexError: list index out of range

**Comment by Koterwong** [comment]
#71 看下这个问题。

**Comment by gjj444** [comment]
可是我的添加简体中文语言包还是这个问题

**Comment by BaiTaiBai** [comment]
我的也已经添加过中文包了

**Comment by gjj444** [comment]
你的解决没有

**Comment by Boot95** [comment]
我的也是这个问题欸，该怎么解决啊  谢谢

**Comment by tae44** [comment]
分辨率的问题 获取的列表长度跟预期的不一样  调节分辨率吧
