### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by fish1024** [Skyexu/TopSup#90]
小白一枚，学了跳一跳之后真的是程序员拯救世界！
边看教程，边百度，这个问题不知道怎么解决？问题可以识别，选项就出错了？
采用方式 1 获取截图
-- 方法2： 题目+选项搜索结果计数法 --
Question:  外号“飞人″的NBA著名球星是?

Traceback (most recent call last):
  File "C:\Users\K4450\Desktop\111\TopSup-master\TopSup-master\GetQuestionTessAndroid.py", line 28, in <module>
    methods.run_algorithm(1, question, choices)
  File "C:\Users\K4450\Desktop\111\TopSup-master\TopSup-master\common\methods.py", line 51, in run_algorithm
    open_webbrowser_count(question, choices)
  File "C:\Users\K4450\Desktop\111\TopSup-master\TopSup-master\common\methods.py", line 16, in open_webbrowser_count
    if '涓嶆槸' in question:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)

**Comment by yinan-1** [comment]
我这个是cmd的问题吗？
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>C:\Users\Administrator\Desktop\TopSup-master\GetQuestionT
essAndroid.py
采用方式 1 获取截图
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\TopSup-master\GetQuestionTessAndroid.py",
 line 20, in <module>
    question, choices = ocr.ocr_img(img)
  File "C:\Users\Administrator\Desktop\TopSup-master\common\ocr.py", line 76, in
 ocr_img
    question = pytesseract.image_to_string(question_im, lang='chi_sim', config=t
essdata_dir_config)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\sit
e-packages\pytesseract\pytesseract.py", line 125, in image_to_string
    raise TesseractError(status, errors)
pytesseract.pytesseract.TesseractError: (1, 'Error opening data file C:\\Program
 Files\\Tesseract-OCR\\tessdata/chi_sim.traineddata')

C:\Users\Administrator>C:\Users\Administrator\Desktop\TopSup-master\GetQuestionT
essAndroid.py

**Comment by FRANKzsx** [comment]
@yinan-1 @fish1024 第一个问题，截图位置没截对吧，调整截图位置，在ocr.py文件里
第二个问题，你没下中文包，所以pytesseract 识别不了，他不是提示缺少chi_sim.traineddata
项目readme里面有说明，你去下载后放那个路劲
