### ISSUE TITLE
新手求救！！从没见过的错误：filename，directory name，or volume label syntax incorrect.

### ISSUE THREAD

**Issue by DotWang** [Skyexu/TopSup#92]
```
C:\Users\ww\Desktop\QA\TopSup-master>python GetQuestionTessAndroid.py
采用方式 1 获取截图
Traceback (most recent call last):
  File "GetQuestionTessAndroid.py", line 20, in <module>
    question, choices = ocr.ocr_img(img)
  File "C:\Users\ww\Desktop\QA\TopSup-master\common\ocr.py", line 76, in ocr_img
    question = pytesseract.image_to_string(question_im, lang='chi_sim', config=tessdata_dir_config)
  File "C:\Users\ww\AppData\Local\Programs\Python\Python36\lib\site-packages\pytesseract\pytesseract.py", line 125, in image_to_string
    raise TesseractError(status, errors)
pytesseract.pytesseract.TesseractError: (1, 'The filename, directory name, or volume label syntax is incorrect.')
```

**Comment by bluefutureworld** [comment]
相同，求抱大佬腿

**Comment by yinan-1** [comment]
没装中文OCR包

**Comment by DotWang** [comment]
@yinan-1 之前我记得勾选了Chinese-Simplified和英文及法语（因为好像出过法语题），现在我只勾选Chinese-Simplified，还是报相同的错，不知道为啥。。
